#!/system/bin/sh

model=`getprop ro.product.model`
mount -o remount,rw /system
rm /system/usr/keylayout/gpio-keys.kl
if [ "$model" = "LG-D320" ] || [ "$model" = "LG-D320n" ]; then
	ln -s /system/usr/keylayout/gpio-keys_d320.kl /system/usr/keylayout/gpio-keys.kl 
elif [ "$model" = "LG-MS323" ]; then
	ln -s /system/usr/keylayout/gpio-keys_ms323.kl /system/usr/keylayout/gpio-keys.kl
else
	ln -s /system/usr/keylayout/gpio-keys_d325.kl /system/usr/keylayout/gpio-keys.kl
fi


mount -o remount,ro /system


